include required("conveyor-beta.conf")

app {
  signing-key = ${env.SIGNING_KEY}

  site {
    copy-to = "github:Joshlha/kindling"
    github {
      pages-branch = "gh-pages-beta"
      oauth-token = ${env.OAUTH_TOKEN}
    }
  }
}
