include required("https://raw.githubusercontent.com/hydraulic-software/conveyor/master/configs/jvm/extract-native-libraries.conf")
include required("generated.conveyor.conf")

app {
  display-name = "Kindling Beta"
  rdns-name = "io.github.inductiveautomation.kindling.beta"
  vcs-url = "github.com/CorbinH/kindling"
  vendor = "IA Support Applications"
  license = "MIT"

  jvm {
    modules += java.desktop
    modules += java.sql
    modules += java.logging
    modules += java.naming
    modules += java.xml
    modules += jdk.zipfs
    modules += jdk.crypto.ec
    modules += jdk.unsupported

    // not in applicationDefaultJvmArgs, so not captured by generated.conveyor.conf
    options += "--add-opens=java.base/sun.misc=ALL-UNNAMED"
  }

  icons = "src/main/resources/beta-logo.svg"

  site {
    extra-header-html = """
        <link rel=icon href=icon.svg sizes="any" type="image/svg+xml">
    """
  }

  file-associations = [
    .data application/data,
    .gwbk application/gwbk,
    .idb application/idb,
    .json application/json,
    .log text/log,
    .modl application/modl,
    .script application/script,
    .txt text/plain,
    .zip application/zip,
  ]

  mac {
    info-plist {
      LSMinimumSystemVersion = 14.0
    }
  }
}

conveyor.compatibility-level = 18
